"use client";
import { FormEvent, useCallback, useEffect, useMemo, useRef, useState } from "react";
import { createClient } from "@/app/utils/supabase/client";
import { useSpace } from "@/app/space/space-shell";
type Message = { id: string; sender_id: string; content: string; created_at: string; delivered_at: string | null; seen_at: string | null };
export default function ChatPage() {
 const { space, profile, partner, loading } = useSpace(); const supabase = useMemo(() => createClient(), []); const [messages, setMessages] = useState<Message[]>([]); const [text, setText] = useState(""); const [status, setStatus] = useState<"loading" | "ready" | "error">("loading"); const [sending, setSending] = useState(false); const [error, setError] = useState(""); const [partnerLastSeen, setPartnerLastSeen] = useState<string | null>(null); const endRef = useRef<HTMLDivElement>(null);
 const addMessage = useCallback((message: Message) => setMessages((current) => current.some((item) => item.id === message.id) ? current : [...current, message]), []);
 const replaceMessage = useCallback((message: Message) => setMessages((current) => current.map((item) => item.id === message.id ? message : item)), []);
 const markSeen = useCallback(async () => { if (!space) return; await supabase.rpc("mark_messages_seen", { target_space_id: space.id }); }, [space, supabase]);
 const loadMessages = useCallback(async () => { if (!space) return; setStatus("loading"); const [{ data, error: queryError }, { data: members }] = await Promise.all([supabase.from("messages").select("id, sender_id, content, created_at, delivered_at, seen_at").eq("space_id", space.id).order("created_at", { ascending: true }).limit(200), supabase.from("space_members").select("user_id, last_seen_at").eq("space_id", space.id)]); if (queryError) { console.info("Unable to load messages", queryError.message); setStatus("error"); return; } setMessages(data ?? []); setPartnerLastSeen(members?.find((member) => member.user_id !== profile?.id)?.last_seen_at ?? null); setStatus("ready"); if (document.visibilityState === "visible") void markSeen(); }, [markSeen, profile?.id, space, supabase]);
 useEffect(() => { const timer = window.setTimeout(() => void loadMessages(), 0); if (!space) return () => window.clearTimeout(timer); const channel = supabase.channel(`space-messages-${space.id}`).on("postgres_changes", { event: "INSERT", schema: "public", table: "messages", filter: `space_id=eq.${space.id}` }, (payload) => { const message = payload.new as Message; addMessage(message); if (message.sender_id !== profile?.id) { void supabase.rpc("mark_messages_delivered", { target_space_id: space.id }); if (document.visibilityState === "visible") void markSeen(); } }).on("postgres_changes", { event: "UPDATE", schema: "public", table: "messages", filter: `space_id=eq.${space.id}` }, (payload) => replaceMessage(payload.new as Message)).on("postgres_changes", { event: "UPDATE", schema: "public", table: "space_members", filter: `space_id=eq.${space.id}` }, (payload) => { const member = payload.new as { user_id: string; last_seen_at: string | null }; if (member.user_id !== profile?.id) setPartnerLastSeen(member.last_seen_at); }).subscribe(); const onVisible = () => { if (document.visibilityState === "visible") void markSeen(); }; document.addEventListener("visibilitychange", onVisible); return () => { window.clearTimeout(timer); document.removeEventListener("visibilitychange", onVisible); void supabase.removeChannel(channel); }; }, [addMessage, loadMessages, markSeen, profile?.id, replaceMessage, space, supabase]);
 useEffect(() => { endRef.current?.scrollIntoView({ behavior: "smooth" }); }, [messages]);
 async function send(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!space || !profile || !text.trim() || sending) return; setSending(true); setError(""); const { data, error: insertError } = await supabase.from("messages").insert({ space_id: space.id, sender_id: profile.id, content: text.trim() }).select("id, sender_id, content, created_at, delivered_at, seen_at").single(); if (insertError) { console.info("Unable to send message", insertError.message); setError("Your message wasn’t sent. Please try again."); } else { addMessage(data); setText(""); } setSending(false); }
 if (loading || !space) return <main className="content"><p className="eyebrow">Chat</p><h1>Loading conversation…</h1></main>;
 return <main className="chat-page"><header className="chat-header"><p className="eyebrow">Private conversation</p><h1>{partner ? `You & ${partner.display_name}` : "Just the two of you"}</h1>{partner && <p className="last-seen">{partnerLastSeen ? `Last seen ${new Intl.DateTimeFormat(undefined, { hour: "numeric", minute: "2-digit", weekday: "short" }).format(new Date(partnerLastSeen))}` : "Not active in chat yet"}</p>}</header><section className="conversation" aria-live="polite">{status === "loading" && <p className="chat-empty">Loading your conversation…</p>}{status === "error" && <p className="chat-empty">We couldn’t load messages. <button onClick={() => void loadMessages()}>Try again</button></p>}{status === "ready" && messages.length === 0 && <p className="chat-empty">Nothing here yet. Say hello when you’re ready.</p>}{messages.map((message) => { const mine = message.sender_id === profile?.id; const receipt = message.seen_at ? "✓✓ Seen" : message.delivered_at ? "✓✓ Delivered" : "✓ Sent"; return <div className={mine ? "message mine" : "message"} key={message.id}><p>{message.content}</p><time dateTime={message.created_at}>{mine ? "You" : partner?.display_name ?? "Partner"} · {new Intl.DateTimeFormat(undefined, { hour: "numeric", minute: "2-digit" }).format(new Date(message.created_at))}{mine && <span className={message.seen_at ? "receipt seen" : "receipt"}> · {receipt}</span>}</time></div>; })}<div ref={endRef} /></section><form className="composer" onSubmit={send}><label className="sr-only" htmlFor="message">Message</label><input id="message" value={text} onChange={(event) => setText(event.target.value)} placeholder="Write a message" maxLength={2000} disabled={sending} autoComplete="off" /><button className="button" disabled={!text.trim() || sending}>{sending ? "Sending…" : "Send"}</button>{error && <p className="form-error" role="alert">{error}</p>}</form></main>;
}
